import type {
  StandingDirective, AssignmentDirective, Deliverable, OperationalHistoryEntry, Gate,
  Team, TeamMembership,
} from '../domain/entities';

/**
 * Phase 2 constitutional objects, reconciled to the approved baseline.
 * Standing Directives carry canonical ST-SD-00X identifiers. Team and Team Membership
 * are first-class objects (TEAM-001, TEAM-002). Operational History activation events
 * are preserved independently. Nothing here originates constitutional authority.
 */

// ---- Standing Directives (canonical ST-SD-00X v1) ----
export const standingDirectives: StandingDirective[] = [
  { id: 'sdr-001', directiveId: 'ST-SD-001', agent: 'ai-sos', title: 'Constitutional guardianship', version: 'v1', governingAuthority: 'Sonja (Product Owner)', governingDecision: 'dec-0007', text: 'Constitutional guardian, reconciliation, divergence detection, dependency analysis, and governance advice. Protects and advises Product Owner authority; does not exercise it.', supersededHistory: [], status: 'Current', authorityStatus: 'approved', demonstration: false },
  { id: 'sdr-002', directiveId: 'ST-SD-002', agent: 'ai-scs', title: 'SCS build authority', version: 'v1', governingAuthority: 'Sonja (Product Owner)', governingDecision: 'dec-0007', text: 'SCS architecture, design, implementation, testing, repository delivery, and technical documentation. Is not SCS and holds no constitutional authority.', supersededHistory: [], status: 'Current', authorityStatus: 'approved', demonstration: false },
  { id: 'sdr-003', directiveId: 'ST-SD-003', agent: 'ai-ckl', title: 'Kidlytics advisory authority', version: 'v1', governingAuthority: 'Sonja (Product Owner)', governingDecision: 'dec-0008', text: 'ChatGPT Kidlytics — advisory support, product architecture, specifications, challenge, review, and cross-artifact reconciliation. Does not replace Product Owner approval.', supersededHistory: [], status: 'Current', authorityStatus: 'approved', demonstration: false },
  { id: 'sdr-004', directiveId: 'ST-SD-004', agent: 'ai-ckp', title: 'Kidlytics prototype authority', version: 'v1', governingAuthority: 'Sonja (Product Owner)', governingDecision: 'dec-0009', text: 'Claude Kidlytics Prototype — prototype design, implementation, testing, synchronization, and repository delivery. Does not replace Product Owner approval.', supersededHistory: [], status: 'Current', authorityStatus: 'approved', demonstration: false },
  { id: 'sdr-005', directiveId: 'ST-SD-005', agent: 'ai-cia', title: 'Kidlytics invitation authority', version: 'v1', governingAuthority: 'Sonja (Product Owner)', governingDecision: 'dec-0008', text: 'Claude Kidlytics Invitation AI Agent — invitation-site evaluation, app evaluation, reviewer-perspective simulation, and feedback synthesis. May not change architecture, canonical language, or product decisions.', supersededHistory: [], status: 'Current', authorityStatus: 'approved', demonstration: false },
  // AGENT-006/#CKL-R — approved and Current by the Product Owner ruling (2026-07-25).
  { id: 'sdr-006', directiveId: 'ST-SD-006', agent: 'ai-cklr', title: 'Kidlytics competitive research authority', version: 'v1', governingAuthority: 'Sonja (Product Owner)', governingDecision: 'dec-cklr-activation', text: 'Kidlytics Competitive Research Agent — evidence-based competitive and market research supporting Kidlytics, performed ONLY when authorized through an approved Assignment Directive: identify direct and adjacent competitors; examine market positioning; compare capabilities and pricing; evaluate trust/safety, AI, financial, and court-related/child-support/co-parenting positioning; identify gaps and strategic opportunities; collect and cite verifiable evidence; distinguish verified fact, inference, open question, and recommendation; prepare findings for Product Owner review. Advisory only — holds no product-decision or approval authority and may not begin research without an approved Assignment Directive.', supersededHistory: ['Reconciled from proposed PROPOSED-ST-SD-CKL-R upon Product Owner approval (2026-07-25).'], status: 'Current', authorityStatus: 'approved', demonstration: false },
];

// ---- Assignment Directives (ST-ADR). The reconciliation directive's canonical
// identifier is Product-Owner-pending and is NOT originated by #SCS. ----
export const assignmentDirectives: AssignmentDirective[] = [
  {
    id: 'adr-001', directiveId: 'ST-ADR-2026-001', agent: 'ai-scs', title: 'Deliver the Team Command Center',
    status: 'Closed — accepted (Phase 1 Functional Demonstration Complete)',
    standingDirective: 'sdr-002', deliverable: 'dlv-001', reviewGate: 'rgate-001', productOwnerDecision: 'dec-0014',
    authorityStatus: 'approved', demonstration: false,
  },
  {
    id: 'adr-002', directiveId: 'ST-ADR-2026-002', agent: 'ai-scs', title: 'Implement Phase 2 — Constitutional Governance',
    status: 'Closed — accepted (reconciled baseline, Product Owner acceptance of commit a773bd6)',
    standingDirective: 'sdr-002', deliverable: 'dlv-002', reviewGate: 'rgate-002', productOwnerDecision: 'dec-0011',
    authorityStatus: 'approved', demonstration: false,
  },
  {
    id: 'adr-003', directiveId: 'ST-ADR-2026-003', agent: 'ai-sos', title: 'Constitutional review of Phase 2 implementation',
    status: 'Closed — accepted (constitutional review concluded; reconciliation accepted)',
    standingDirective: 'sdr-001', reviewGate: 'rgate-002', productOwnerDecision: 'dec-0007',
    authorityStatus: 'approved', demonstration: false,
  },
  {
    id: 'adr-004', directiveId: 'Pending Product Owner-authorized ST-ADR identifier', agent: 'ai-scs',
    title: 'Phase 2 Constitutional Reconciliation',
    status: 'Closed — accepted (Product Owner acceptance of commit a773bd6)',
    standingDirective: 'sdr-002', deliverable: 'dlv-003', reviewGate: 'rgate-003',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Governed by the Product Owner Directive "Phase 2 Constitutional Reconciliation" (2026-07-24) and closed by the Product Owner Acceptance Ruling (2026-07-25) accepting commit a773bd6. The canonical Assignment Directive identifier remains Product-Owner-pending — #SCS does not originate or assign it, and this acceptance does NOT assign it. Expected to occupy ST-ADR-2026-004; that number stays RESERVED and unresolved.',
  },
  // AGENT-006/#CKL-R competitive-research assignment — approved & activated by the Product Owner
  // ruling (2026-07-25). Canonical identifier ST-ADR-2026-005 (skips the reserved ST-ADR-2026-004).
  {
    id: 'adr-005', directiveId: 'ST-ADR-2026-005', agent: 'ai-cklr', title: 'Kidlytics Competitive Landscape Research',
    status: 'Active',
    standingDirective: 'sdr-006', deliverable: 'dlv-004', reviewGate: 'rgate-004', productOwnerDecision: 'dec-cklr-research-assignment',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Reconciled from proposed PROPOSED-ST-ADR-CKL-R upon Product Owner approval. Authorizes evidence-based competitive research only; findings are advisory and do not automatically modify Kidlytics or authorize implementation.',
  },
  // Phase 4 — SCS Production Architecture. Authorized (planning only) by the Product Owner
  // Product Continuation & Architecture Directive (2026-07-25). Canonical ST-ADR identifier is
  // Product-Owner-pending (recommended ST-ADR-2026-006, which skips the reserved ST-ADR-2026-004);
  // #SCS does not originate it. Valid independently of #SCS activation.
  {
    id: 'adr-006', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-006)', agent: 'ai-scs',
    title: 'Prepare the SCS Production Architecture & Authorization Package (Phase 4)',
    status: 'Closed — completed & accepted (Phase 4 Production Architecture approved as the authoritative planning baseline; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-005', reviewGate: 'rgate-005', productOwnerDecision: 'dec-scs-phase4',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Phase 4 (architecture & planning) complete and accepted. This did NOT authorize production backend implementation, migration, authentication, integrations, hosting deployment, or go-live — Phase 5 requires a separate Product Owner production-implementation directive.',
  },
  // Phase 5 — Backend Foundation & Persistence. Authorized (narrow) by the Product Owner
  // Production Implementation Authorization Directive (2026-07-25). Canonical ST-ADR identifier
  // Product-Owner-pending (recommended ST-ADR-2026-007); #SCS does not originate it. Valid
  // independently of #SCS activation.
  {
    id: 'adr-007', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-007)', agent: 'ai-scs',
    title: 'SCS Backend Foundation & Persistence Implementation (Phase 5)',
    status: 'Closed — completed & accepted (Phase 5 accepted by Product Owner; runtime-verified; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-006', reviewGate: 'rgate-006', productOwnerDecision: 'dec-scs-phase5',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Phase 5 (backend foundation & persistence) complete and accepted. Did NOT authorize authentication rollout, confidential-data hosting, integrations, deployment, or go-live. Phase 6 is NOT authorized.',
  },
  // SCS Production Baseline v1.0 — documentation/traceability only (Product Owner Baseline
  // Establishment Directive, 2026-07-25). Canonical ST-ADR identifier Product-Owner-pending.
  {
    id: 'adr-008', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-008)', agent: 'ai-scs',
    title: 'Establish SCS Production Baseline v1.0 (documentation & traceability)',
    status: 'Closed — completed & accepted (Baseline v1.0 accepted by Product Owner; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-007', reviewGate: 'rgate-007', productOwnerDecision: 'dec-scs-baseline',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Documentation baseline complete and accepted. Did NOT authorize Phase 6, implementation changes, refactoring, authentication, deployment, or new capabilities, and assigned no canonical identifiers.',
  },
  // SCS Platform Completion Program — planning/roadmap only (Product Owner Platform Completion
  // Mandate, 2026-07-25). Canonical ST-ADR identifier Product-Owner-pending.
  {
    id: 'adr-009', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-009)', agent: 'ai-scs',
    title: 'Establish the SCS Platform Completion Program (roadmap & planning)',
    status: 'Closed — completed & accepted (Completion Program Rev 2 approved by Product Owner; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-008', reviewGate: 'rgate-008', productOwnerDecision: 'dec-scs-completion',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Completion Program Rev 2 (commit b6c9305) approved as the governing SCS Platform Completion Program. Planning/documentation only. Did NOT authorize Phase 6, authentication/authorization, Phase 6 records, confidential data, hosting selection, deployment, integrations, or launch — each requires a separate directive. No canonical identifiers assigned.',
  },
  // Phase 6 Authorization Package — PLANNING record for authorization preparation only (Product
  // Owner Authorization Directive, 2026-07-25). NOT a Phase 6 implementation record. Canonical
  // ST-ADR identifier Product-Owner-pending.
  {
    id: 'adr-010', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-010)', agent: 'ai-scs',
    title: 'Prepare the SCS Phase 6 Authorization Package (planning only)',
    status: 'Closed — completed & accepted (Phase 6 Authorization Package accepted by Product Owner; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-009', reviewGate: 'rgate-009', productOwnerDecision: 'dec-scs-phase6-authpkg',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Phase 6 Authorization Package accepted (commit 51a9557) as the authoritative Phase 6 planning document. Product Owner resolved the Phase 6 decisions (native identity, sessions+MFA, DB session store, no new human users, agents propose-only, PO sole non-delegable authority, Trust≠Security, server-sole authorization boundary, bounded scope). Did NOT authorize Phase 6 implementation and created NO implementation-governed records. No canonical identifiers assigned.',
  },
  // Phase 6 IMPLEMENTATION — Identity, Authority & Trust (Product Owner Implementation Authorization
  // Directive, 2026-07-25). Now permitted to create implementation records. Canonical ST-ADR id pending.
  {
    id: 'adr-011', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-011)', agent: 'ai-scs',
    title: 'SCS Phase 6 Implementation — Identity, Authority & Trust',
    status: 'Closed — completed & accepted (Phase 6 accepted by Product Owner; runtime-verified; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-010', reviewGate: 'rgate-010', productOwnerDecision: 'dec-scs-phase6-impl',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Phase 6 (Identity, Authority, Trust attribution) complete and accepted. Runtime-verified in CI (commits 30d4216 implementation, 9c0e33c reported state, preserved as accepted revisions). Did NOT authorize Phase 7, confidential data, hosting, deployment, or launch.',
  },
  // Phase 7 AUTHORIZATION PACKAGE — planning only (Product Owner Authorization Directive, 2026-07-25).
  // Planning-preparation assignment; may create ONLY planning records (assignment/deliverable/gate/
  // operational-history) — NO decision record, NO implementation records. Canonical ST-ADR id pending.
  {
    id: 'adr-012', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-012)', agent: 'ai-scs',
    title: 'Prepare the SCS Phase 7 Authorization Package (planning only)',
    status: 'Closed — completed & accepted (Phase 7 Authorization Package approved by Product Owner 2026-07-25; canonical ST-ADR identifier remains Product-Owner-pending)',
    standingDirective: 'sdr-002', deliverable: 'dlv-011', reviewGate: 'rgate-011',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Planning and authorization-preparation ONLY. Phase 7 Authorization Package APPROVED by Product Owner (commit 24b97b9 preserved as the accepted revision). Product Owner decisions approved: (1) server is sole constitutional authority for derived state — clients present/cache/propose only; (2) governed command vocabulary propose/approve/accept/activate/reject/supersede/archive/restore/retire accepted (sequencing is a Phase 7 concern); (3) separate schema_version and derivation_version governance, never merged; (4) responsibility matrix is the permanent architectural reference — boundary-blurring capabilities require PO architectural review; (5) migration ledger is a permanent artifact until client constitutional derivation is eliminated; (6) deterministic replay is a constitutional requirement; (7) approval-gated transitions remain server-enforced, Product-Owner-only. Required Addition produced: CONSTITUTIONAL_DERIVATION_PRINCIPLES.md (permanent constitutional architecture). Authorized NO implementation; created NO implementation-governed records; no canonical identifiers originated. See SCS_PHASE_7_AUTHORIZATION_PACKAGE.md.',
  },
  // Phase 7 IMPLEMENTATION — Server-Side Constitutional Derivation & Canonical State Authority
  // (Product Owner Implementation Authorization Directive, 2026-07-25). Implementation records now
  // permitted. Canonical ST-ADR id remains Product-Owner-pending. #SCS does not self-accept.
  {
    id: 'adr-013', directiveId: 'Pending Product Owner-authorized ST-ADR identifier (recommended: ST-ADR-2026-013)', agent: 'ai-scs',
    title: 'SCS Phase 7 Implementation — Server-Side Constitutional Derivation & Canonical State Authority',
    status: 'Active — implementation runtime-verified in CI; submitted to the Phase 7 Implementation Review gate; awaiting Product Owner disposition',
    standingDirective: 'sdr-002', deliverable: 'dlv-012', reviewGate: 'rgate-012',
    authorityStatus: 'approved', demonstration: false,
    notes: 'Implements the approved Phase 7 scope only: server-side canonical constitutional derivation engine (Scs\\Derivation — deterministic, reproducible, explainable, versioned), canonical state authority, the complete governed command architecture (propose/approve/accept/activate/reject/supersede/archive/restore/retire on a server-validated StateMachine), client→server migration of the constitutional derivations (agent state + team roll-up now server-canonical; parity-pinned), independent derivation_version/schema_version governance, replay + drift store (migration 0003), and the mandatory regression suite. Runtime-verified in CI (PHP 8.2 + MySQL 8). Complies with the Authentication & Authority and Constitutional Derivation Principles. Excludes notifications, hosting, deployment, confidential data, Technical Audit Log (Phase 8), monitoring, production, launch. #SCS does not self-accept.',
  },
];

export const deliverables: Deliverable[] = [
  { id: 'dlv-001', deliverableId: 'ST-DLV-2026-001', title: 'Team Command Center (Phase 1 Functional Demonstration)', assignmentDirective: 'adr-001', reviewGate: 'rgate-001', status: 'Accepted', authorityStatus: 'approved', demonstration: false },
  { id: 'dlv-002', deliverableId: 'ST-DLV-2026-002', title: 'Phase 2 — Constitutional Governance Implementation', assignmentDirective: 'adr-002', reviewGate: 'rgate-002', status: 'Accepted (Product Owner acceptance of commit a773bd6)', authorityStatus: 'approved', demonstration: false },
  { id: 'dlv-003', deliverableId: 'ST-DLV-2026-003', title: 'Phase 2 Constitutional Reconciliation', assignmentDirective: 'adr-004', reviewGate: 'rgate-003', status: 'Accepted (Product Owner acceptance of commit a773bd6)', authorityStatus: 'approved', demonstration: false },
  // Required deliverable for ST-ADR-2026-005. Pending #CKL-R's research; NOT yet in review.
  { id: 'dlv-004', deliverableId: 'ST-DLV-2026-004', title: 'Kidlytics Competitive Landscape Report', assignmentDirective: 'adr-005', reviewGate: 'rgate-004', status: 'Pending — awaiting #CKL-R research', authorityStatus: 'approved', demonstration: false, notes: 'Must separate verified facts, reasonable inferences, unresolved questions, research limitations, and recommendations requiring Product Owner or #CKL review. Includes a complete source register.' },
  // Phase 4 deliverable — submitted for Product Owner review at the SCS Production Architecture Review gate.
  { id: 'dlv-005', deliverableId: 'ST-DLV-2026-005', title: 'SCS Production Architecture & Authorization Package (Rev 2 — corrected)', assignmentDirective: 'adr-006', reviewGate: 'rgate-005', status: 'Accepted (Product Owner) — authoritative production-architecture planning baseline', authorityStatus: 'approved', demonstration: false, notes: 'Accepted 2026-07-25 as the authoritative production-architecture planning baseline (PHASE_4_PRODUCTION_ARCHITECTURE.md + PHASE_4_CORRECTIONS_REV2.md). Acceptance of the architecture does NOT authorize production implementation; Phase 5 requires a separate Product Owner directive.' },
  // Phase 5 deliverable — submitted for the SCS Backend Foundation & Persistence Review gate.
  { id: 'dlv-006', deliverableId: 'ST-DLV-2026-006', title: 'SCS Backend Foundation & Persistence Implementation Package', assignmentDirective: 'adr-007', reviewGate: 'rgate-006', status: 'Accepted (Product Owner) — Phase 5 Backend Foundation & Persistence; runtime-verified (PHP 8.2 + MySQL 8, end-to-end green)', authorityStatus: 'approved', demonstration: false, notes: 'Accepted 2026-07-25 by Product Owner ruling. Runtime verification (GitHub Actions run 30168236724, commit 2ae3a64) passed end-to-end: migrations, PHPUnit (persistence, optimistic-concurrency 409, idempotency, FK rejection, transaction rollback, import), backend boot, and RemoteAdapter ↔ real PHP/MySQL. Nestify hosting verification remains unresolved (noted, not blocking). See PHASE_5_IMPLEMENTATION.md.' },
  // SCS Production Baseline v1.0 — documentation deliverable, submitted for review.
  { id: 'dlv-007', deliverableId: 'ST-DLV-2026-007', title: 'SCS Production Baseline v1.0', assignmentDirective: 'adr-008', reviewGate: 'rgate-007', status: 'Accepted (Product Owner) — authoritative implementation baseline (comparison point for all future reviews)', authorityStatus: 'approved', demonstration: false, notes: 'Accepted 2026-07-25. Baseline v1.0 is IMMUTABLE except through future approved supersession. New governance classification "Baseline" recorded (distinct from ST-ADR/ST-DEC/ST-DLV/ST-OPH); Baseline Identifier is Product-Owner-pending. See SCS_PRODUCTION_BASELINE_v1.0.md.' },
  // SCS Platform Completion Program package — submitted for review.
  { id: 'dlv-008', deliverableId: 'ST-DLV-2026-008', title: 'SCS Platform Completion Program (Rev 2 — capability-based, governance-first)', assignmentDirective: 'adr-009', reviewGate: 'rgate-008', status: 'Accepted (Product Owner) — governing SCS Platform Completion Program (Rev 2, commit b6c9305)', authorityStatus: 'approved', demonstration: false, notes: 'Accepted 2026-07-25. Rev 2 is the governing roadmap: capability hierarchy (Domain→Capability→Requirements→Evidence), governance-first domains, distinct Trust/Security, consolidated Operational Readiness, Platform Architecture + Platform Evolution capabilities. Completion estimate ~25% approved as an order-of-magnitude planning measure (not a release forecast). Approval authorizes the roadmap only — no implementation phase or launch. See SCS_PLATFORM_COMPLETION_PROGRAM.md.' },
  // Phase 6 Authorization Package — planning deliverable, submitted for review.
  { id: 'dlv-009', deliverableId: 'ST-DLV-2026-009', title: 'SCS Phase 6 Authorization Package (planning)', assignmentDirective: 'adr-010', reviewGate: 'rgate-009', status: 'Accepted (Product Owner) — authoritative Phase 6 planning document (commit 51a9557). Phase 6 implementation NOT authorized.', authorityStatus: 'approved', demonstration: false, notes: 'Accepted 2026-07-25 with Product Owner decisions resolved. Required addition produced: AUTHENTICATION_AND_AUTHORITY_PRINCIPLES.md (constitutional architecture). Architecture only — authorizes no implementation; no Phase 6 implementation records. See SCS_PHASE_6_AUTHORIZATION_PACKAGE.md.' },
  // Phase 6 implementation deliverable — submitted for review (runtime-verified in CI).
  { id: 'dlv-010', deliverableId: 'ST-DLV-2026-010', title: 'SCS Phase 6 Implementation — Identity, Authority & Trust', assignmentDirective: 'adr-011', reviewGate: 'rgate-010', status: 'Accepted — Phase 6 Implemented, Verified & Accepted by Product Owner (2026-07-25)', authorityStatus: 'approved', demonstration: false, notes: 'Identity (Argon2id, server sessions, TOTP MFA mandatory for PO, lifecycle/rotation/revocation/expiry/recovery/lockout), Authority (roles/permissions, server-side approval boundary, PO-only approve, agents propose-only, admins cannot set authority), Trust (authenticated attribution seam; NOT full Technical Audit Log = Phase 8). Runtime-verified in CI (commit 30d4216 green: migration 0002, PHPUnit 21, auth e2e 3, persistence e2e 5, frontend 39; all mandatory rejection scenarios enforced). Accepted with Product Owner decisions: Administrator MFA optional in Phase 6; infrastructure rate-limiting deferred to Phase 10; client login UI outside Phase 6; full Technical Audit Log remains Phase 8. Does NOT authorize Phase 7, confidential data, hosting, deployment, or launch. See SCS_PHASE_6_IMPLEMENTATION.md.' },
  { id: 'dlv-011', deliverableId: 'ST-DLV-2026-011', title: 'SCS Phase 7 Authorization Package (planning)', assignmentDirective: 'adr-012', reviewGate: 'rgate-011', status: 'Accepted (Product Owner, 2026-07-25) — governing Phase 7 planning document (commit 24b97b9). Phase 7 implementation NOT authorized.', authorityStatus: 'approved', demonstration: false, notes: 'Planning-only authorization package for Phase 7 — Server-Side Constitutional Derivation & Canonical State Authority. APPROVED as the governing Phase 7 planning document. Seven Product Owner decisions approved (server sole constitutional authority; governed command vocabulary propose…retire; separate schema_version/derivation_version; permanent responsibility matrix; permanent migration ledger; deterministic replay as a constitutional requirement; server-enforced Product-Owner-only approval boundary). Required Addition produced: CONSTITUTIONAL_DERIVATION_PRINCIPLES.md (permanent constitutional architecture). Authorizes NO implementation; created NO implementation-governed records. Next governed document is a separate Product Owner Phase 7 Implementation Authorization Directive. See SCS_PHASE_7_AUTHORIZATION_PACKAGE.md.' },
  { id: 'dlv-012', deliverableId: 'ST-DLV-2026-012', title: 'SCS Phase 7 Implementation — Server-Side Constitutional Derivation & Canonical State Authority', assignmentDirective: 'adr-013', reviewGate: 'rgate-012', status: 'In review — Phase 7 Implementation Review (runtime-verified in CI, PHP 8.2 + MySQL 8; client/server derivation parity green)', authorityStatus: 'reported', demonstration: false, notes: 'Server-side canonical derivation engine (Scs\\Derivation), canonical state authority, complete governed command architecture on a server-validated state machine (propose/approve/accept/activate/reject/supersede/archive/restore/retire), client→server migration (agent state + team roll-up server-canonical, parity-pinned), independent derivation_version/schema_version governance, replay + drift store (migration 0003), and mandatory regression suite. Runtime-verified in CI: DerivationTest, CommandTest, PersistenceTest, AuthTest, plus the client/server parity e2e (server output === client engine). #SCS does not self-accept. See SCS_PHASE_7_IMPLEMENTATION.md and MIGRATION_LEDGER.md.' },
];

export const reviewGates: Gate[] = [
  { id: 'rgate-001', name: 'Team Command Center review', requiresOwnerApproval: true, status: 'Approved', decisionRef: 'dec-0014', authorityStatus: 'approved', demonstration: false },
  { id: 'rgate-002', name: 'Phase 2 review', requiresOwnerApproval: true, status: 'Approved', authorityStatus: 'approved', demonstration: false },
  { id: 'rgate-003', name: 'Reconciliation review', requiresOwnerApproval: true, status: 'Approved', authorityStatus: 'approved', demonstration: false },
  // Review gate for ST-DLV-2026-004. Product Owner is primary authority; #CKL is a product-review participant.
  { id: 'rgate-004', name: 'Competitive Research Review', requiresOwnerApproval: true, status: 'Open — pending deliverable', authorityStatus: 'approved', demonstration: false },
  // Phase 4 review gate. Product Owner is primary authority. Acceptance of the architecture does
  // NOT automatically authorize production implementation (separate ruling required).
  { id: 'rgate-005', name: 'SCS Production Architecture Review', requiresOwnerApproval: true, status: 'Approved — Phase 4 Production Architecture accepted (gate closed). Architecturally ready for Phase 5; Phase 5 implementation NOT authorized by this approval.', authorityStatus: 'approved', demonstration: false },
  // Phase 5 review gate. Product Owner authority. Acceptance of Phase 5 does not auto-authorize Phase 6.
  { id: 'rgate-006', name: 'SCS Backend Foundation & Persistence Review', requiresOwnerApproval: true, status: 'Approved — Phase 5 accepted by Product Owner (gate closed). Phase 6 not authorized.', authorityStatus: 'approved', demonstration: false },
  // Baseline documentation review gate. Acceptance does not authorize Phase 6.
  { id: 'rgate-007', name: 'SCS Production Baseline v1.0 Review', requiresOwnerApproval: true, status: 'Approved & closed — Baseline v1.0 accepted (authoritative). Phase 6 not authorized.', authorityStatus: 'approved', demonstration: false },
  // Completion Program review gate. Approval of the roadmap does not authorize any implementation phase or launch.
  { id: 'rgate-008', name: 'SCS Platform Completion Program Review', requiresOwnerApproval: true, status: 'Approved & closed — Completion Program Rev 2 accepted (governing roadmap). Phase 6 not authorized.', authorityStatus: 'approved', demonstration: false },
  // Phase 6 Authorization Package review gate (PLANNING). Acceptance does not authorize Phase 6 implementation.
  { id: 'rgate-009', name: 'Phase 6 Authorization Package Review', requiresOwnerApproval: true, status: 'Approved & closed — Phase 6 Authorization Package accepted (authoritative planning document). Phase 6 implementation NOT authorized.', authorityStatus: 'approved', demonstration: false },
  // Phase 6 implementation review gate. #SCS does not self-accept; awaits Product Owner disposition.
  { id: 'rgate-010', name: 'Phase 6 Implementation Review', requiresOwnerApproval: true, status: 'Closed — Approved by Product Owner (2026-07-25); Phase 6 Implemented, Verified & Accepted', authorityStatus: 'approved', demonstration: false },
  { id: 'rgate-011', name: 'Phase 7 Authorization Package Review', requiresOwnerApproval: true, status: 'Approved & closed — Phase 7 Authorization Package accepted (governing planning document). Phase 7 implementation NOT authorized.', authorityStatus: 'approved', demonstration: false },
  { id: 'rgate-012', name: 'Phase 7 Implementation Review', requiresOwnerApproval: true, status: 'Open — pending Product Owner review (implementation runtime-verified in CI; #SCS does not self-accept)', authorityStatus: 'proposed', demonstration: false },
];

// ---- Operational History — activation events preserved independently ----
export const operationalHistory: OperationalHistoryEntry[] = [
  { id: 'oh-001', entryId: 'ST-OPH-2026-001', date: '2026-07-24', agent: 'ai-scs', summary: 'Team Command Center delivered and accepted as Phase 1 Functional Demonstration Complete.', evidenceType: 'Deliverable accepted', relatedObject: 'dlv-001', authorityStatus: 'approved', demonstration: false },
  { id: 'oh-002', entryId: 'ST-OPH-2026-002', date: '2026-07-24', agent: 'ai-scs', summary: 'Phase 2 — Constitutional Governance Implementation submitted for Product Owner review.', evidenceType: 'Deliverable submitted', relatedObject: 'dlv-002', authorityStatus: 'reported', demonstration: false },
  { id: 'oh-003', entryId: 'ST-OPH-2026-003', date: '2026-07-24', agent: 'ai-sos', summary: 'Constitutional review of Phase 2 implementation in progress.', evidenceType: 'Governance review', relatedObject: 'adr-003', authorityStatus: 'reported', demonstration: false },
  // AGENT-005 — two distinct activation events, preserved independently.
  { id: 'oh-004', entryId: 'ST-OPH-2026-004', date: '2026-07-24', agent: 'ai-cia', summary: 'AGENT-005 (#CIA) Standing Directive ST-SD-005 v1 recorded Current.', evidenceType: 'Constitutional activation', relatedObject: 'sdr-005', authorityStatus: 'approved', demonstration: false },
  { id: 'oh-005', entryId: 'ST-OPH-2026-005', date: '2026-07-24', agent: 'ai-cia', summary: 'AGENT-005 (#CIA) Product Owner acceptance, verification, closure, and organizational readiness (TEAM-001 membership Active).', evidenceType: 'Product Owner acceptance & organizational readiness', relatedObject: 'tm-005', authorityStatus: 'approved', demonstration: false },
  // Activation events for the previously-governed agents.
  { id: 'oh-006', entryId: 'ST-OPH-2026-006', date: '2026-07-24', agent: 'ai-sos', summary: 'AGENT-001 (#SOS) Standing Directive ST-SD-001 v1 Current; TEAM-002 membership Active.', evidenceType: 'Constitutional activation', relatedObject: 'sdr-001', authorityStatus: 'proposed', demonstration: false, notes: 'Pending Product Owner approval — NOT authoritative activation evidence; retained for Product Owner review.' },
  { id: 'oh-007', entryId: 'ST-OPH-2026-007', date: '2026-07-24', agent: 'ai-scs', summary: 'AGENT-002 (#SCS) Standing Directive ST-SD-002 v1 Current; TEAM-002 membership Active.', evidenceType: 'Constitutional activation', relatedObject: 'sdr-002', authorityStatus: 'proposed', demonstration: false, notes: 'Pending Product Owner approval — NOT authoritative activation evidence; retained for Product Owner review.' },
  { id: 'oh-008', entryId: 'ST-OPH-2026-008', date: '2026-07-24', agent: 'ai-ckl', summary: 'AGENT-003 (#CKL) Standing Directive ST-SD-003 v1 Current; TEAM-001 membership Active.', evidenceType: 'Constitutional activation', relatedObject: 'sdr-003', authorityStatus: 'proposed', demonstration: false, notes: 'Pending Product Owner approval — NOT authoritative activation evidence; retained for Product Owner review.' },
  { id: 'oh-009', entryId: 'ST-OPH-2026-009', date: '2026-07-24', agent: 'ai-ckp', summary: 'AGENT-004 (#CKP) Standing Directive ST-SD-004 v1 Current; TEAM-001 membership Active.', evidenceType: 'Constitutional activation', relatedObject: 'sdr-004', authorityStatus: 'proposed', demonstration: false, notes: 'Pending Product Owner approval — NOT authoritative activation evidence; retained for Product Owner review.' },
  // Product Owner Acceptance Ruling (2026-07-25) — records acceptance & closure only.
  // Deliberately NOT a "Constitutional activation" event and tied to no single agent, so it
  // activates no agent. It does not approve ST-OPH-2026-006..009 and does not assign the ST-ADR identifier.
  { id: 'oh-010', entryId: 'ST-OPH-2026-010', date: '2026-07-25', summary: 'Product Owner accepted commit a773bd6 as the Phase 2 reconciliation baseline; the Phase 2 implementation-reconciliation cycle is closed and the Constitutional State Derivation Engine implementation is Verified and Accepted. This acceptance does NOT approve ST-OPH-2026-006 through ST-OPH-2026-009, activates no agent (AGENT-001..004 remain Pending activation), and does not assign the reconciliation ST-ADR identifier.', evidenceType: 'Product Owner acceptance & closure', relatedObject: 'dlv-003', authorityStatus: 'approved', demonstration: false },
  // Milestone: Transition from Constitutional Foundation to Product Execution (Approved).
  // Records the strategic transition only — activates no agent and reopens nothing.
  // AGENT-006/#CKL-R authoritative activation event — approved by the Product Owner ruling (2026-07-25).
  { id: 'oh-012', entryId: 'ST-OPH-2026-012', date: '2026-07-25', agent: 'ai-cklr', summary: 'AGENT-006 (#CKL-R) constitutionally activated by express Product Owner ruling: AGENT-006 identity approved; Standing Directive ST-SD-006 recorded Current; Team Membership TM-009 recorded Active in TEAM-001; Product Owner activation decision recorded. #CKL-R transitions from Proposed / Pending Onboarding to Activated — Available — Awaiting Assignment. No approved active Assignment Directive exists; competitive research remains prohibited until a separate Assignment Directive is approved. Reconciled from proposed PROPOSED-ST-OPH-CKL-R; does not determine the disposition of ST-OPH-2026-006..009.', evidenceType: 'Constitutional activation', relatedObject: 'sdr-006', authorityStatus: 'approved', demonstration: false },
  // Product Owner disposition — Completion Program Rev 2 accepted. Recorded in Operational History
  // per the acceptance directive; canonical ST-OPH identifier is Product-Owner-pending (no improvised
  // identifier). Not an activation event; tied to no agent.
  { id: 'oh-013', entryId: 'Pending Product Owner-authorized ST-OPH identifier (Completion Program Rev 2 acceptance)', date: '2026-07-25', summary: 'Product Owner APPROVED the SCS Platform Completion Program Rev 2 (commit b6c9305) as the governing completion roadmap. Six architectural decisions approved: (1) capability-based completion model (Domain→Capability→Requirements→Evidence) is authoritative; (2) domain-based completion measurement (initial weighting; recalibrate only via approved revision); (3) Trust and Security are distinct domains; (4) Platform Architecture governance (API/versioning/extensibility/evolution) is a required capability; (5) SDK strategy = Not Applicable for current scope (reconsider if SCS exposes external developer interfaces); (6) Platform Evolution governance required before final production acceptance. Completion estimate ~25% approved as an order-of-magnitude planning measure. Baseline v1.0 unaltered. Phase 6, confidential data, hosting selection, deployment, and launch NOT authorized. Canonical identifiers for these decisions await the separately-resolved identifier standard.', evidenceType: 'Product Owner disposition & acceptance', authorityStatus: 'approved', demonstration: false },
  // Product Owner disposition — Phase 6 Authorization Package accepted with decisions resolved.
  // Recorded in Operational History; canonical ST-OPH identifier Product-Owner-pending (no improvised id).
  { id: 'oh-014', entryId: 'Pending Product Owner-authorized ST-OPH identifier (Phase 6 Authorization Package acceptance)', date: '2026-07-25', summary: 'Product Owner ACCEPTED the SCS Phase 6 Authorization Package (commit 51a9557) as the authoritative Phase 6 planning document — implementation NOT authorized. Decisions resolved: (1) native SCS identity, no external IdP in Phase 6; (2) email/password + Argon2id + server-managed sessions (HttpOnly/Secure/SameSite=Strict), no JWT; (3) MFA mandatory for Product Owner, later required for Administrators, optional for future users; (4) database-backed sessions (Redis a future optimization); (5) no additional authenticated human users in Phase 6 (PO, Administrator, Agent, Service only); (6) AI agents are never human identities — scoped credentials, propose-only, may never approve/accept/activate/elevate; (7) Product Owner sole non-delegable constitutional approval authority; (8) Trust remains permanently separate from Security; (9) server-sole authorization boundary (clients propose, server validates, PO approves) — rejected scenarios become mandatory regression tests; (10) bounded scope (no notifications, hosting, external identity, deployment, confidential data). Required addition produced: AUTHENTICATION_AND_AUTHORITY_PRINCIPLES.md (constitutional architecture). Canonical identifiers deferred to the separate identifier standard. Baseline v1.0 unaltered.', evidenceType: 'Product Owner disposition & acceptance', authorityStatus: 'approved', demonstration: false },
  { id: 'oh-011', entryId: 'ST-OPH-2026-011', date: '2026-07-25', summary: 'Milestone — Transition from Constitutional Foundation to Product Execution (Approved). The Constitutional State Derivation implementation initiative is complete (architecture → implementation → reconciliation → constitutional review → Product Owner acceptance → verification → recording → operational closure). The Constitutional State Derivation Engine and the SCS constitutional models are now accepted OPERATIONAL INFRASTRUCTURE, not an active implementation initiative. Kidlytics is restored as the primary governed product initiative; the Constitution now supports the product. Reserved and unaffected: authorized activation history for AGENT-001..004; disposition of ST-OPH-2026-006..009; assignment of the reconciliation ST-ADR identifier; future organizational evidence review for AGENT-003/#CKL and AGENT-004/#CKP — these remain separate Product Owner governance work and do not delay Kidlytics.', evidenceType: 'Product Owner milestone — strategic transition', authorityStatus: 'approved', demonstration: false },
  { id: 'oh-018', entryId: 'Pending Product Owner-authorized ST-OPH identifier (Phase 7 Implementation submission)', date: '2026-07-25', agent: 'ai-scs', summary: 'Product Owner authorized Phase 7 implementation. #SCS implemented Server-Side Constitutional Derivation & Canonical State Authority and submitted ST-DLV-2026-012 to the Phase 7 Implementation Review gate (rgate-012). Delivered: the canonical server derivation engine (Scs\\Derivation — deterministic, reproducible, explainable, versioned; a faithful port of the client engine, parity-pinned); canonical state authority (authority fields change only via governed commands + Product Owner approval; clients cannot author derived state); the COMPLETE governed command architecture on a server-validated state machine — propose/approve/accept/activate/reject/supersede/archive/restore/retire — each validating authority, current state, preconditions, the approval boundary, concurrency and idempotency, and preserving attribution; client→server migration of the constitutional derivations (agent state + team roll-up now server-canonical; MIGRATION_LEDGER.md permanent artifact); independent derivation_version/schema_version governance with compatibility, replay, and a drift store (migration 0003); and the mandatory regression suite. Runtime-verified end-to-end in CI (PHP 8.2 + MySQL 8): DerivationTest, CommandTest, PersistenceTest, AuthTest, and the client/server derivation PARITY e2e (server output === client engine per fixture). Complies with the Authentication & Authority and Constitutional Derivation Principles. Excludes notifications, hosting, deployment, confidential data, Technical Audit Log (Phase 8), monitoring, production, and launch. #SCS did NOT self-accept. Canonical identifiers remain Product-Owner-pending.', evidenceType: 'Implementation deliverable submitted', relatedObject: 'dlv-012', authorityStatus: 'reported', demonstration: false },
  { id: 'oh-017', entryId: 'Pending Product Owner-authorized ST-OPH identifier (Phase 7 Authorization Package acceptance)', date: '2026-07-25', agent: 'ai-scs', summary: 'Product Owner APPROVED the SCS Phase 7 Authorization Package (commit 24b97b9) as the governing Phase 7 planning document. ST-DLV-2026-011 accepted; Phase 7 Authorization Package Review Gate (rgate-011) closed Approved; planning assignment adr-012 closed completed & accepted. Seven Product Owner decisions approved: (1) the server is the sole constitutional authority for derived platform state — clients may present, cache, and propose, but may never become the authoritative source of constitutional state; (2) the governed command vocabulary propose/approve/accept/activate/reject/supersede/archive/restore/retire is accepted as the constitutional command vocabulary for SCS (implementation sequencing is a Phase 7 concern); (3) schema_version and derivation_version are governed separately and never merged; (4) the client/server responsibility matrix is the permanent architectural reference — any future capability that blurs the boundary requires a Product Owner architectural review; (5) the migration ledger is a permanent artifact — every client-derived capability migrated to the server is recorded until client constitutional derivation is fully eliminated; (6) deterministic replay is a constitutional requirement (same authoritative inputs + command history + derivation version must reproduce the same constitutional state); (7) all approval-gated transitions remain server-enforced and Product-Owner-only — no client, administrator, AI agent, automation, or API consumer may perform constitutional approval. Required Addition produced: CONSTITUTIONAL_DERIVATION_PRINCIPLES.md — permanent constitutional architecture doctrine (companion to Authentication & Authority Principles), to precede any Phase 7 implementation. Implementation Status: Phase 7 Authorization Package Accepted; Phase 7 IMPLEMENTATION NOT AUTHORIZED — no implementation assignment, no implementation review gate, no implementation-governed records created. Baseline v1.0 unchanged; confidential data, deployment, and launch not authorized. The next governed document shall be a separate Product Owner Phase 7 Implementation Authorization Directive; until it is issued, no Phase 7 implementation work begins. Canonical identifiers remain Product-Owner-pending.', evidenceType: 'Product Owner disposition & acceptance', relatedObject: 'dlv-011', authorityStatus: 'approved', demonstration: false },
  { id: 'oh-016', entryId: 'Pending Product Owner-authorized ST-OPH identifier (Phase 7 Authorization Package preparation)', date: '2026-07-25', agent: 'ai-scs', summary: 'Product Owner authorized preparation of the SCS Phase 7 Authorization Package (planning only). #SCS submitted SCS_PHASE_7_AUTHORIZATION_PACKAGE.md (ST-DLV-2026-011) to the Phase 7 Authorization Package Review gate (rgate-011). Phase 7 mission: the server becomes the single constitutional authority for all derived platform state — the server derives, the client presents, the Product Owner approves. The package specifies (planning only) server-side constitutional derivation, canonical state authority, the complete governed command architecture (propose/approve/accept/activate/reject/supersede/archive/restore/retire — defined, not implemented), the client/server responsibility matrix, derivation version governance, the constitutional state transition model, parity strategy, performance architecture, failure handling, a security review, a verification strategy (defined, NOT executed), traceability, an updated 11-item Product Owner decision queue, and Phase 7 readiness findings. Planning only — authorizes NO implementation; created ONLY planning records (this assignment adr-012, deliverable dlv-011, gate rgate-011, this entry) per the directive\'s closed list; NO decision record; NO implementation records; NO server-side derivation implemented; NO deployment/hosting/confidential-data/launch. Baseline v1.0 unaltered. #SCS did not self-authorize implementation. Canonical identifiers remain Product-Owner-pending.', evidenceType: 'Planning deliverable submitted', relatedObject: 'dlv-011', authorityStatus: 'reported', demonstration: false },
  { id: 'oh-015', entryId: 'Pending Product Owner-authorized ST-OPH identifier (Phase 6 Implementation acceptance)', date: '2026-07-25', agent: 'ai-scs', summary: 'Product Owner ACCEPTED SCS Phase 6 Implementation — Identity, Authority & Trust — as Implemented, Verified & Accepted. ST-DLV-2026-010 accepted; Phase 6 Implementation Review Gate (rgate-010) closed Approved; assignment (adr-011) closed completed & accepted. Scope accepted: Identity (Argon2id credentials, server-managed HttpOnly/Secure/SameSite=Strict sessions, TOTP MFA mandatory for Product Owner, session rotation/revocation/idle+absolute expiry/recovery/lockout); Authority (role/permission matrix, server-side approval boundary, Product-Owner-only approve with fresh MFA, agents propose-only, administrators cannot set authority via data); Trust (authenticated attribution seam — mutation_attributions/request-ids/auth_events). Runtime-verified in CI on real PHP 8.2 + MySQL 8 (commit 30d4216 green; commit 9c0e33c reported state); both preserved as accepted revisions. Product Owner decisions recorded: Administrator MFA remains optional in Phase 6 (mandatory deferred); infrastructure rate-limiting deferred to Phase 10 (application-layer lockout sufficient for Phase 6); client login UI outside Phase 6 scope; full Technical Audit Log remains Phase 8. This acceptance does NOT authorize Phase 7, confidential data, hosting selection, deployment, or launch. Baseline v1.0 unaltered. Canonical ST-OPH/ST-DEC/ST-ADR/ST-DLV identifiers remain Product-Owner-pending until the identifier standard is resolved.', evidenceType: 'Product Owner disposition & acceptance', relatedObject: 'dlv-010', authorityStatus: 'approved', demonstration: false },
];

// ---- Team and Team Membership (first-class objects) ----
export const teams: Team[] = [
  { id: 'team-001', teamId: 'TEAM-001', name: 'ShockTheory Agent Team', status: 'Active', authorityStatus: 'approved', demonstration: false },
  { id: 'team-002', teamId: 'TEAM-002', name: 'SCS Team', status: 'Active', authorityStatus: 'approved', demonstration: false },
];

export const teamMemberships: TeamMembership[] = [
  // Displaced implementation records — #SOS/#SCS approved membership is TEAM-002 (SCS Team).
  // Retained for traceability; NOT current governing membership; excluded from derivation.
  { id: 'tm-001', membershipId: 'TM-001', agent: 'ai-sos', team: 'team-001', status: 'Superseded — reconciled to TEAM-002', effectiveDate: '2026-07-24', authorityStatus: 'superseded', demonstration: false, notes: 'Displaced implementation record; #SOS approved membership is TEAM-002.' },
  { id: 'tm-002', membershipId: 'TM-002', agent: 'ai-scs', team: 'team-001', status: 'Superseded — reconciled to TEAM-002', effectiveDate: '2026-07-24', authorityStatus: 'superseded', demonstration: false, notes: 'Displaced implementation record; #SCS approved membership is TEAM-002.' },
  { id: 'tm-003', membershipId: 'TM-003', agent: 'ai-ckl', team: 'team-001', status: 'Active', effectiveDate: '2026-07-24', authorityStatus: 'approved', demonstration: false },
  { id: 'tm-004', membershipId: 'TM-004', agent: 'ai-ckp', team: 'team-001', status: 'Active', effectiveDate: '2026-07-24', authorityStatus: 'approved', demonstration: false },
  { id: 'tm-005', membershipId: 'TM-005', agent: 'ai-cia', team: 'team-001', status: 'Active', effectiveDate: '2026-07-24', authorityStatus: 'approved', demonstration: false },
  // TEAM-002 (SCS Team) — approved memberships. Membership records only: they do not
  // merge identities, transfer authority, alter Standing Directives, or create powers.
  { id: 'tm-006', membershipId: 'TM-006', agent: 'po-sonja', team: 'team-002', status: 'Active', effectiveDate: '2026-07-24', authorityStatus: 'approved', demonstration: false, notes: 'Product Owner — Sonja Ross (not an agent).' },
  { id: 'tm-007', membershipId: 'TM-007', agent: 'ai-sos', team: 'team-002', status: 'Active', effectiveDate: '2026-07-24', authorityStatus: 'approved', demonstration: false },
  { id: 'tm-008', membershipId: 'TM-008', agent: 'ai-scs', team: 'team-002', status: 'Active', effectiveDate: '2026-07-24', authorityStatus: 'approved', demonstration: false },
  // AGENT-006/#CKL-R — approved TEAM-001 membership by the Product Owner ruling (2026-07-25).
  { id: 'tm-009', membershipId: 'TM-009', agent: 'ai-cklr', team: 'team-001', status: 'Active', effectiveDate: '2026-07-25', authorityStatus: 'approved', demonstration: false, notes: 'Reconciled from proposed PROPOSED-TM-CKL-R upon Product Owner approval. Active membership does not, by itself, authorize research.' },
];
