import type { WorkspaceBackup, CollectionName } from '../storage/StorageAdapter';
import { SCHEMA_VERSION } from '../domain/schemaVersion';
import { interimDecisions } from './decisions';
import {
  standingDirectives, assignmentDirectives, deliverables, operationalHistory, reviewGates,
  teams, teamMemberships,
} from './directives';
import type {
  OSSystem,
  Product,
  Publication,
  PublicationPhase,
  Gate,
  AICollaborator,
  Assignment,
  Artifact,
  CanonicalStatement,
  NextAction,
  Update,
} from '../domain/entities';

/**
 * SEED / DEMO DATA — clearly labeled (isSeed: true).
 *
 * Contains ONLY what the SCS specification states. Nothing is invented to look
 * complete (Non-Negotiable Rule #11); unknown values are left empty and remain
 * visibly unresolved. Authority states reflect reality — mostly `reported`/
 * `proposed`, never `approved` unless the spec explicitly states approval.
 * The Product Owner reviews and corrects this data. See docs/seed-data.md.
 */

const osSystems: OSSystem[] = [
  {
    id: 'os-sapdos',
    name: 'ShockTheory AI Product Development Operating System',
    acronym: 'SAPDOS',
    purpose: 'Operating system for AI-driven product development within ShockTheory OS.',
    authority: 'ShockTheory OS',
    version: '—',
    status: 'Active',
    owner: 'ShockTheory OS',
    dependencies: [],
    relatedProducts: ['prod-kidlytics', 'prod-civicai'],
    changeHistory: [],
    methodologyMaturity: 'Validated in Kidlytics',
    authorityStatus: 'reported',
    confidence: 'medium',
    notes: 'Seed record — details to be confirmed by Product Owner.',
  },
  {
    id: 'os-stacl',
    name: 'ShockTheory AI Command Language',
    acronym: 'STACL',
    purpose: 'Command language governing AI collaboration and sync codes across ShockTheory OS.',
    authority: 'ShockTheory OS',
    version: '—',
    status: 'Active',
    owner: 'ShockTheory OS',
    dependencies: [],
    relatedProducts: [],
    changeHistory: [],
    authorityStatus: 'reported',
    confidence: 'medium',
    notes: 'Owns the adopted sync codes (ST-SYNC, ST-LOCK, ST-BENCHMARK, ST-REVIEW, ST-DIVERGENCE, ST-OS).',
  },
  {
    id: 'os-stp',
    name: 'ShockTheory Publication System',
    acronym: 'STP',
    purpose: 'Governs the three official publication families and their phase-gated progress.',
    authority: 'ShockTheory OS',
    version: '—',
    status: 'Active',
    owner: 'ShockTheory OS',
    dependencies: [],
    relatedProducts: [],
    changeHistory: [],
    authorityStatus: 'reported',
    confidence: 'medium',
  },
  {
    id: 'os-sos',
    name: '#SOS — Chief of Staff and Constitutional Guardian',
    acronym: '#SOS',
    purpose: 'Advises and governs within ShockTheory OS. Does not approve on the Product Owner’s behalf.',
    authority: 'ShockTheory OS',
    version: '—',
    status: 'Active',
    owner: 'ShockTheory OS',
    dependencies: [],
    relatedProducts: [],
    changeHistory: [],
    authorityStatus: 'reported',
    confidence: 'medium',
  },
  {
    id: 'os-scs',
    name: 'ShockTheory Constitutional System',
    acronym: 'SCS',
    purpose: 'The living constitutional command, awareness, and artifact-navigation system for ShockTheory OS.',
    authority: 'ShockTheory OS',
    version: 'v0.1 MVP',
    status: 'Operational infrastructure — Constitutional State Derivation accepted',
    owner: 'Sonja Ross',
    dependencies: ['os-sapdos', 'os-stacl', 'os-stp', 'os-sos'],
    relatedProducts: ['prod-kidlytics', 'prod-civicai'],
    changeHistory: ['Phase 0 architecture approved', 'Phase 1 functional shell', 'Phase 2 Constitutional State Derivation accepted (commit a773bd6)', 'Transition to Product Execution — SCS constitutional capability operational', 'Phase 1 functional demonstration closed (accepted, demonstration scope)', 'Phase 4 Production Architecture authorized (planning only)', 'Phase 4 Production Architecture accepted (planning baseline; architecturally ready for Phase 5; Phase 5 not authorized)', 'Phase 5 Backend Foundation & Persistence accepted (runtime-verified PHP 8.2 + MySQL 8)', 'Production Baseline v1.0 established (accepted, immutable)', 'Platform Completion Program Rev 2 accepted (governing roadmap)', 'Phase 6 Authorization Package accepted (planning)', 'Phase 6 Implementation — Identity, Authority & Trust — accepted (Implemented, Verified & Accepted 2026-07-25; dev/test runtime-verified; Phase 7 not authorized)'],
    authorityStatus: 'approved',
    constitutionalReview: false,
    confidence: 'high',
    notes: 'This record reflects SCS CONSTITUTIONAL CAPABILITY (accepted, verified, operational). SCS SOFTWARE PRODUCT MATURITY is a separate dimension tracked on the prod-scs product record (functional demonstration; production architecture in Phase 4). "Operational infrastructure" is not a substitute for software-production status.',
  },
];

const products: Product[] = [
  {
    id: 'prod-scs',
    name: 'SCS Platform',
    ecosystem: 'ShockTheory · Internal software platform',
    purpose: 'The active software platform that implements approved ShockTheory OS concepts, stores and links authoritative records, derives governed organizational and product state, and presents dashboards, action queues, history, traceability, contradictions, and portfolio status — tracking its own development through the same governed structures.',
    lifecycleStage: 'Phase 6 Accepted · Awaiting Phase 7 Authorization',
    status: 'Active — internal platform. Phase 6 (Identity, Authority & Trust) Implemented, Verified & Accepted · Baseline v1.0 Established · Completion Program Rev 2 Governing (~40% accepted). Phase 7 Authorization Package (server-side derivation) in Product Owner review — planning only; Phase 7 implementation NOT authorized. Not Operational, Not Production, not launched.',
    owner: 'Sonja Ross (Product Owner) · #SCS (steward/implementer)',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
    notes: 'Status dimensions (independent): Portfolio Status: Active · Implementation Status: Phase 6 Accepted (Identity/Authority/Trust attribution — dev/test runtime-verified; production operationalization pending) · Baseline Status: Production Baseline v1.0 — Accepted (authoritative comparison point for every future review; immutable except through approved supersession; Baseline Identifier Product-Owner-pending) · Operational Status: Not Operational · Production Status: Not Production · Commercial Status: Internal · Lifecycle: Phase 6 Accepted, Awaiting Phase 7 Authorization. Completion Program Status: Rev 2 Governing (~40% accepted) · Launch Status: Not Authorized · Phase 7 Status: Not Authorized. Phase 6 acceptance decisions: Administrator MFA optional in Phase 6; infrastructure rate-limiting deferred to Phase 10; client login UI outside Phase 6; full Technical Audit Log remains Phase 8. Constitutional capability (separate dimension): Accepted, Verified, Operational. Phase/work/readiness derive from linked governed records; no additional readiness is inferred. Completion is required (Platform Completion Mandate); phase progression remains governed.',
  },
  {
    id: 'prod-kidlytics',
    name: 'Kidlytics',
    ecosystem: 'ShockTheory',
    purpose: 'Lead product — three Volume 01 playbooks in flight (Experience, Workflow, Component).',
    lifecycleStage: 'Active development',
    status: 'Active',
    owner: 'Sonja Ross',
    currentBenchmark: undefined,
    authorityStatus: 'reported',
    confidence: 'medium',
    notes: 'Purpose statement to be confirmed by Product Owner.',
  },
  {
    id: 'prod-civicai',
    name: 'CivicAI',
    ecosystem: 'ShockTheory',
    purpose: 'Second product line — no publications recorded yet; awaiting its first playbook.',
    lifecycleStage: 'Early',
    status: 'Active',
    owner: 'Sonja Ross',
    authorityStatus: 'reported',
    confidence: 'low',
    notes: 'Purpose statement to be confirmed by Product Owner.',
  },
];

const publications: Publication[] = [
  {
    id: 'pub-cue',
    family: 'experience',
    volume: '01',
    title: 'Cue',
    product: 'prod-kidlytics',
    purpose: 'Kidlytics Experience Playbook · Volume 01 · Cue.',
    status: 'In progress',
    version: '—',
    currentPhase: 'phase-cue-5',
    currentGate: 'gate-cue-5',
    canonicalUsed: [],
    confidentiality: 'Confidential - Internal Use Only',
    authorityStatus: 'proposed',
    confidence: 'high',
    notes: 'Phase 5 authorized after Phase 4 approval.',
  },
  {
    id: 'pub-chipn',
    family: 'workflow',
    volume: '01',
    title: 'Chip’n',
    product: 'prod-kidlytics',
    purpose: 'Kidlytics Workflow Playbook · Volume 01 · Chip’n.',
    status: 'Discovery — decisions pending',
    version: '—',
    currentPhase: 'phase-chipn-1',
    currentGate: undefined,
    canonicalUsed: [],
    confidentiality: 'Confidential - Internal Use Only',
    authorityStatus: 'proposed',
    confidence: 'high',
    notes: 'Discovery and lifecycle decisions pending.',
  },
  {
    id: 'pub-approval',
    family: 'component',
    volume: '01',
    title: 'Approval',
    product: 'prod-kidlytics',
    purpose: 'Kidlytics Component Playbook · Volume 01 · Approval.',
    status: 'Planned — not yet started',
    version: '—',
    canonicalUsed: [],
    confidentiality: 'Confidential - Internal Use Only',
    authorityStatus: 'reported',
    confidence: 'high',
    notes: 'Planned, not yet started.',
  },
];

// Cue is at Phase 5, with Phases 1–4 approved. Faithful to “Phase 5 authorized after
// Phase 4 approval.” Phase labels follow the suggested STP sequence.
const cuePhaseNames = ['Discovery', 'Foundation', 'Direction', 'Core', 'Complexity', 'Final Assembly'];
const publicationPhases: PublicationPhase[] = [
  ...cuePhaseNames.map((name, i): PublicationPhase => ({
    id: `phase-cue-${i + 1}`,
    publication: 'pub-cue',
    name,
    order: i + 1,
    status: i + 1 < 5 ? 'Approved' : i + 1 === 5 ? 'In progress' : 'Pending',
    authorityStatus: i + 1 < 5 ? 'approved' : 'proposed',
    confidence: 'medium',
  })),
  {
    id: 'phase-chipn-1',
    publication: 'pub-chipn',
    name: 'Discovery',
    order: 1,
    status: 'In progress — decisions pending',
    authorityStatus: 'proposed',
    confidence: 'medium',
  },
];

const gates: Gate[] = [
  {
    id: 'gate-cue-4',
    publication: 'pub-cue',
    phase: 'phase-cue-4',
    name: 'Phase 4 approval',
    requiresOwnerApproval: true,
    status: 'Approved',
    authorityStatus: 'approved',
    confidence: 'high',
  },
  {
    id: 'gate-cue-5',
    publication: 'pub-cue',
    phase: 'phase-cue-5',
    name: 'Phase 5 gate',
    requiresOwnerApproval: true,
    status: 'Open',
    authorityStatus: 'proposed',
    confidence: 'medium',
  },
];

// Governed agent register (ST-LOCK). '#' = agent/governed role. No agent may
// approve its own proposals; AI recommends, never approves.
const aiCollaborators: AICollaborator[] = [
  {
    id: 'ai-sos',
    name: '#SOS',
    role: 'Constitutional guardian, reconciliation, divergence detection, dependency analysis, and governance advice.',
    standingResponsibility: 'Protects and advises Product Owner authority; does not exercise it.',
    authorityScope: 'Advises and governs; may not approve. No agent may approve its own proposals.',
    syncState: 'Synchronized',
    lastSynced: '2026-07-24',
    governingRecord: 'dec-0007',
    openQuestions: [],
    conflictsDetected: [],
    authorityStatus: 'reported',
    confidence: 'high',
  },
  {
    id: 'ai-scs',
    name: '#SCS',
    role: 'SCS architecture, design, implementation, testing, repository delivery, and technical documentation.',
    modelProvider: 'Claude (Anthropic)',
    authorityScope: 'Designs and builds SCS but is not SCS and holds no constitutional authority. May not approve.',
    currentTask: 'Phase 7 AUTHORIZATION PACKAGE prepared (planning only) — server-side constitutional derivation & canonical state authority fully specified (derivation architecture, complete governed command model, client/server responsibility matrix, state transitions, version governance, parity, failure handling, security, verification strategy not executed, 11-item PO decision queue). Submitted ST-DLV-2026-011 to the Phase 7 Authorization Package Review (rgate-011). Only planning records created; NO decision record, NO implementation, NO server-side derivation, NO deployment/hosting/confidential data/launch. #SCS did not self-authorize.',
    waitingState: 'Product Owner review (Phase 7 Authorization Package Review)',
    expectedNextAction: 'Await Product Owner disposition of the Phase 7 Authorization Package. Begin no Phase 7 implementation / server-side derivation / hosting / deployment / confidential-data / launch work until separately authorized.',
    syncState: 'Synchronized',
    lastSynced: '2026-07-25',
    governingRecord: 'dec-0007',
    openQuestions: [],
    conflictsDetected: [],
    authorityStatus: 'reported',
    confidence: 'high',
  },
  {
    id: 'ai-ckl',
    name: '#CKL',
    role: 'ChatGPT Kidlytics — Product Owner advisory support, product architecture, specifications, challenge, review, and cross-artifact reconciliation.',
    modelProvider: 'ChatGPT (OpenAI)',
    assignedProduct: 'prod-kidlytics',
    authorityScope: 'Advises and reconciles Kidlytics product work; does not replace Product Owner approval.',
    syncState: 'Aligned',
    lastSynced: '2026-07-20',
    governingRecord: 'dec-0008',
    openQuestions: [],
    conflictsDetected: [],
    authorityStatus: 'reported',
    confidence: 'medium',
  },
  {
    id: 'ai-ckp',
    name: '#CKP',
    role: 'Claude Kidlytics Prototype — prototype design, implementation, testing, synchronization, and repository delivery.',
    modelProvider: 'Claude (Anthropic)',
    assignedProduct: 'prod-kidlytics',
    authorityScope: 'Prototypes and delivers Kidlytics prototype work; does not replace Product Owner approval.',
    syncState: 'Aligned',
    lastSynced: '2026-07-22',
    governingRecord: 'dec-0009',
    openQuestions: [],
    conflictsDetected: [],
    authorityStatus: 'reported',
    confidence: 'medium',
  },
  {
    id: 'ai-cia',
    name: '#CIA',
    role: 'Claude Kidlytics Invitation AI Agent — invitation-experience review, invitation-site evaluation, app evaluation, reviewer-perspective simulation, and feedback synthesis.',
    modelProvider: 'Claude (Anthropic)',
    assignedProduct: 'prod-kidlytics',
    authorityScope: 'Evaluates and synthesizes the Kidlytics invitation experience; may not change architecture, canonical language, or product decisions.',
    currentTask: 'Independent evaluation of Kidlytics — usability, clarity, trust, product communication, onboarding, and workflow.',
    syncState: 'Not Required',
    governingRecord: 'dec-0008',
    openQuestions: [],
    conflictsDetected: [],
    authorityStatus: 'reported',
    confidence: 'medium',
    notes: 'AGENT-005 — constitutionally activated (state derived from ST-SD-005 v1 Current, approved Product Owner activation authority, Operational History activation events ST-OPH-2026-004/005, and active TEAM-001 membership).',
  },
  {
    id: 'ai-cklr',
    name: '#CKL-R',
    role: 'Kidlytics Competitive Research Agent — evidence-based competitive and market research supporting Kidlytics, performed only when authorized through an approved Assignment Directive.',
    modelProvider: 'ChatGPT (OpenAI)',
    assignedProduct: 'prod-kidlytics',
    authorityScope: 'Advisory research only. May not change architecture, modify the prototype, implement features, make product decisions, direct other agents, or begin research without an approved Assignment Directive.',
    standingResponsibility: 'Evidence-based competitive and market research supporting Kidlytics; submits findings for Product Owner review.',
    currentTask: 'Kidlytics Competitive Landscape Research (ST-ADR-2026-005) — evidence-based competitive research; deliverable ST-DLV-2026-004 pending.',
    expectedNextAction: 'Deliver the Kidlytics Competitive Landscape Report for Product Owner review (Competitive Research Review gate).',
    syncState: 'Synchronized',
    lastSynced: '2026-07-25',
    governingRecord: 'dec-cklr-activation',
    openQuestions: [],
    conflictsDetected: [],
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
    notes: 'AGENT-006 — constitutionally activated by express Product Owner ruling (2026-07-25). State derived from ST-SD-006 v1 Current, approved Product Owner activation authority, Operational History activation event ST-OPH-2026-012, and active TEAM-001 membership TM-009. Available — Awaiting Assignment; competitive research is prohibited until a separate Assignment Directive is approved.',
  },
];

const assignments: Assignment[] = [
  {
    id: 'assign-scs-build',
    collaborator: 'ai-scs',
    task: 'Phase 2 Constitutional Governance & Derivation — reconciliation accepted.',
    waitingState: 'Accepted (commit a773bd6)',
    expectedOutput: 'Reconciled Phase 2 implementation — accepted by the Product Owner.',
    directive: 'adr-002',
    reviewGate: 'Phase 2 review',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'assign-sos-govern',
    collaborator: 'ai-sos',
    task: 'Constitutional review of Phase 2 implementation.',
    waitingState: 'Review concluded — reconciliation accepted',
    expectedOutput: 'Governance assessment — concluded; reconciliation accepted.',
    directive: 'adr-003',
    reviewGate: 'Phase 2 review',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'medium',
  },
];

const artifacts: Artifact[] = [
  {
    id: 'art-drive',
    name: 'SCS — Google Drive folder',
    type: 'Folder',
    area: 'SCS',
    version: '—',
    storageProvider: 'google-drive',
    openLink:
      'https://drive.google.com/drive/folders/1-6YATDDHFaZ_Ema3v7_UgqYW9LQPZ9Pe?usp=drive_link',
    linkHealth: 'unverified',
    confidentiality: 'Confidential - Internal Use Only',
    authorityStatus: 'reported',
    confidence: 'high',
  },
  {
    id: 'art-github',
    name: 'SCS — GitHub repository',
    type: 'Repository',
    area: 'SCS',
    version: '—',
    storageProvider: 'github',
    repoURL: 'https://github.com/shocktheory/SCSGithub',
    linkHealth: 'ok',
    confidentiality: 'Confidential - Internal Use Only',
    authorityStatus: 'verified',
    confidence: 'high',
  },
  {
    id: 'art-production',
    name: 'ShockTheory OS — production site',
    type: 'Production URL',
    area: 'SCS',
    version: '—',
    storageProvider: 'production',
    productionURL: 'https://shocktheoryos.com',
    linkHealth: 'unverified',
    confidentiality: 'Confidential - Internal Use Only',
    authorityStatus: 'reported',
    confidence: 'high',
  },
];

// Class I canonical statements are named in the spec, but their exact wording is
// NOT provided here — so it is left blank rather than invented (Rule #11).
const canonicalStatements: CanonicalStatement[] = [
  {
    id: 'canon-creed',
    statement: '',
    classification: 'I',
    stableName: 'The Creed',
    reclassificationHistory: [],
    authorityStatus: 'reported',
    confidence: 'low',
    notes: 'Canonical wording to be entered by Product Owner — not invented.',
  },
  {
    id: 'canon-promise',
    statement: '',
    classification: 'I',
    stableName: 'The Promise',
    reclassificationHistory: [],
    authorityStatus: 'reported',
    confidence: 'low',
    notes: 'Canonical wording to be entered by Product Owner — not invented.',
  },
  {
    id: 'canon-approval-boundary',
    statement: '',
    classification: 'I',
    stableName: 'The Approval Boundary',
    reclassificationHistory: [],
    authorityStatus: 'reported',
    confidence: 'low',
    notes: 'Canonical wording to be entered by Product Owner — not invented.',
  },
];

// Constitutional activity — only real, honest events. Cue's Phase-4 approval is
// spec-stated but undated here, so its date is left empty rather than invented.
const updates: Update[] = [
  {
    id: 'upd-scs-phase7-authpkg',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Product Owner authorized preparation of the SCS Phase 7 Authorization Package (planning only). #SCS submitted SCS_PHASE_7_AUTHORIZATION_PACKAGE.md (ST-DLV-2026-011) to the Phase 7 Authorization Package Review (rgate-011). Phase 7 mission: the server becomes the single constitutional authority for all derived platform state (server derives, client presents, Product Owner approves). The package defines — planning only — server-side constitutional derivation, canonical state authority, the complete governed command architecture (propose/approve/accept/activate/reject/supersede/archive/restore/retire, defined not implemented), the client/server responsibility matrix, derivation version governance, the constitutional state transition model, parity strategy, performance architecture, failure handling, a security review, a verification strategy (defined, NOT executed), traceability, an updated 11-item Product Owner decision queue, and Phase 7 readiness findings (no self-recommendation). Per the directive\'s closed list, ONLY planning records were created (adr-012, dlv-011, rgate-011, oh-016) — NO decision record, NO implementation records. NO server-side derivation implemented; NO deployment/hosting/confidential data/launch. Baseline v1.0 unaltered; canonical identifiers remain Product-Owner-pending. #SCS did not self-authorize implementation.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['adr-012', 'dlv-011', 'rgate-011', 'oh-016', 'prod-scs', 'SCS_PHASE_7_AUTHORIZATION_PACKAGE.md'],
    syncStatus: 'Planning — Phase 7 Authorization Package submitted for review (implementation not authorized)',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase6-accepted',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Phase 6 Implementation Review — APPROVED. Product Owner accepted SCS Phase 6 (Identity, Authority & Trust attribution) as Implemented, Verified & Accepted. Governed record actions recorded: ST-DLV-2026-010 accepted; Phase 6 Implementation Review Gate (rgate-010) closed Approved; assignment adr-011 closed completed & accepted; dec-scs-phase6-impl → Verified and Accepted; Operational History entry recorded (oh-015). Product Owner decisions: Administrator MFA optional in Phase 6; infrastructure rate-limiting deferred to Phase 10; client login UI outside Phase 6; full Technical Audit Log remains Phase 8. As directed, the capability-based Completion Register was updated (Identity + Authority:Roles&Permissions Accepted; Trust/Security/Quality lifted) and the completion estimate recomputed with the approved domain weighting: ~25% → ~40% accepted. Commits 30d4216 and 9c0e33c preserved as accepted revisions. Baseline v1.0 unaltered; canonical identifiers remain Product-Owner-pending. Does NOT authorize Phase 7, confidential data, hosting, deployment, or launch.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-010', 'rgate-010', 'adr-011', 'dec-scs-phase6-impl', 'prod-scs', 'SCS_PLATFORM_COMPLETION_PROGRAM.md'],
    syncStatus: 'Approved — Phase 6 accepted; Completion Register updated (~40%); awaiting Phase 7 authorization',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase6-impl',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Product Owner authorized Phase 6 implementation. #SCS implemented Identity (Argon2id, server-managed sessions, TOTP MFA mandatory for PO, lifecycle/rotation/revocation/expiry/recovery/lockout), Authority (roles/permissions, server-side approval boundary, PO-only approve command, agents propose-only, admins cannot set authority), and Trust (authenticated attribution seam). Runtime-verified end-to-end in CI (PHP 8.2 + MySQL 8, commit 30d4216): migration 0002, PHPUnit (21), auth e2e (3), persistence e2e (5), frontend (39); all mandatory rejection scenarios enforced. Submitted ST-DLV-2026-010 to the Phase 6 Implementation Review. #SCS did NOT self-accept. Excluded: notifications, hosting, deployment, confidential data, external identity, full Technical Audit Log (Phase 8), launch.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: ['dec-scs-phase6-impl'],
    documentsUpdated: [],
    syncStatus: 'Working — Phase 6 implementation runtime-verified; submitted for review',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase6-authpkg-accepted',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Phase 6 Authorization Package Review — APPROVED with Product Owner decisions. The package (commit 51a9557) is accepted as the authoritative Phase 6 planning document; assignment closed, ST-DLV-2026-009 accepted, gate closed. Ten Phase 6 decisions resolved (native identity; email/password + Argon2id + server sessions, no JWT; MFA mandatory for PO; DB session store; no new human users; agents propose-only; PO sole non-delegable authority; Trust≠Security permanent doctrine; server-sole authorization boundary with mandatory regression tests; bounded scope). Required addition produced: AUTHENTICATION_AND_AUTHORITY_PRINCIPLES.md (constitutional architecture). Phase 6 IMPLEMENTATION NOT AUTHORIZED; no implementation records created; Baseline v1.0 unaltered; canonical identifiers deferred.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-009', 'rgate-009', 'adr-010', 'dec-scs-phase6-authpkg'],
    syncStatus: 'Approved — Phase 6 Authorization Package accepted (implementation not authorized)',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase6-authpkg',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'Product Owner authorized preparation of the SCS Phase 6 Authorization Package (planning only). #SCS submitted SCS_PHASE_6_AUTHORIZATION_PACKAGE.md (ST-DLV-2026-009): executive overview, capability breakdown (Identity/Authority/Trust), security & trust architecture, identity model, role/permission matrix, authorization boundary, threat assessment, verification strategy (not executed), traceability, decision queue, and readiness (Phase 6 is architecturally defined and ready for a Product Owner decision). Planning only — NO implementation, NO Phase 6 implementation records, no authentication/authorization code, no deployment, no confidential data, no launch.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: ['dec-scs-phase6-authpkg'],
    documentsUpdated: [],
    syncStatus: 'Planning — Phase 6 Authorization Package submitted for review',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-completion-rev2-accepted',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'SCS Platform Completion Program Review — APPROVED. Product Owner accepted Completion Program Rev 2 (commit b6c9305) as the governing completion roadmap: assignment closed, ST-DLV-2026-008 accepted, review gate closed. Six architectural decisions approved (capability-based model; domain-based measurement; Trust/Security separation; Platform Architecture governance; SDK = Not Applicable; Platform Evolution governance). Completion estimate ~25% approved as an order-of-magnitude planning measure. Canonical identifiers await the separate identifier standard; Baseline v1.0 unaltered. Next governed action: prepare a separate Phase 6 Authorization Directive (which itself does not authorize implementation). NOT authorized: Phase 6, auth, hosting, confidential data, deployment, launch.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-008', 'rgate-008', 'adr-009', 'dec-scs-completion'],
    syncStatus: 'Approved — Completion Program Rev 2 governing & active',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-completion-rev2',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'SCS Platform Completion Program — Product Owner review returned it for architectural refinement (highly favorable direction). #SCS submitted Rev 2: capability-based completion model (Domain→Capability→Requirements→Evidence); added Platform Architecture Completion, consolidated Operational Readiness, added Platform Evolution Governance, separated Platform Trust from Security, and reorganized the narrative around platform domains (governance-first). Strong sections and constitutional constraints preserved. Planning only — no implementation, no Phase 6 records, baseline unaltered.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-008'],
    syncStatus: 'Rev 2 revisions submitted for review',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-completion-mandate',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'Product Owner issued the SCS Platform Completion Mandate — completion of SCS to a secure, operational, production-ready internal platform is now a binding requirement (phase progression stays governed). The SCS Completion Program is authorized for planning. #SCS submitted the SCS Platform Completion Program (ST-DLV-2026-008): completion definition, roadmap (Phases 6–12), Completion Register, Accepted Capability Inventory, current-state assessment (~26% accepted), measurement method, and the proposed Phase 6 package. Planning only — NOT authorized: Phase 6 implementation, authentication, deployment, confidential data, integrations, OS-CAP-001, launch.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: ['dec-scs-completion'],
    documentsUpdated: [],
    syncStatus: 'Authorized for Planning — Completion Program submitted for review',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-baseline-accepted',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'SCS Production Baseline v1.0 Review — APPROVED. Product Owner accepted Baseline v1.0 as the first authoritative implementation baseline and the comparison point for every future review: baseline assignment closed, ST-DLV-2026-007 accepted, review gate closed, SCS product record updated (Production Baseline v1.0 Established; Lifecycle: Awaiting Phase 6 Authorization). New governance classification "Baseline" recorded (distinct from ST-ADR/ST-DEC/ST-DLV/ST-OPH; Baseline Identifier Product-Owner-pending). Baseline is immutable except through approved supersession. Phase 6 NOT authorized; no implementation, architecture, or identifier changes.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-007', 'rgate-007', 'adr-008', 'dec-scs-baseline'],
    syncStatus: 'Approved — Baseline v1.0 accepted (authoritative)',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-baseline-v1',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'Product Owner authorized the SCS Production Baseline v1.0 — an authoritative snapshot of the accepted state following Phase 5 (documentation, traceability, governance). #SCS produced SCS_PRODUCTION_BASELINE_v1.0.md and submitted ST-DLV-2026-007 to the SCS Production Baseline v1.0 Review. Documentation only — no implementation, architecture, or accepted-record changes; no canonical identifiers assigned; Phase 6 not authorized.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: ['dec-scs-baseline'],
    documentsUpdated: [],
    syncStatus: 'Working — baseline documentation (submitted for review)',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase5-accepted',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'SCS Backend Foundation & Persistence Review — APPROVED. Product Owner accepted Phase 5: assignment completed, deliverable ST-DLV-2026-006 accepted, review gate closed, implementation status Phase 5 Accepted. Runtime verification passed end-to-end on PHP 8.2 + MySQL 8. SCS is eligible for Phase 6 authorization. Nestify hosting verification remains unresolved (noted, not blocking). NOT authorized by this ruling: Phase 6, authentication rollout, production deployment, confidential data, public availability, launch.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-006', 'rgate-006', 'adr-007', 'dec-scs-phase5'],
    syncStatus: 'Approved — Phase 5 accepted; eligible for Phase 6 (not authorized)',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase5-returned',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'SCS Backend Foundation & Persistence — Returned for Correction (host runtime verification), then CORRECTED & runtime-verified. The authoring environment has no PHP/MySQL/Docker/network, so #SCS executed the required runtime verification via GitHub Actions on PHP 8.2 + MySQL 8: migrations, PHPUnit (persistence, optimistic-concurrency 409, idempotency, FK rejection, transaction rollback, import), backend boot, and END-TO-END RemoteAdapter ↔ real PHP/MySQL — all green (run 30168236724, commit 2ae3a64). Runtime verification found and fixed a real FastRoute route-order defect. Corrected package resubmitted; records preserved (assignment active, gate open, identifiers Product-Owner-pending); nothing closed or accepted by #SCS.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-006', 'rgate-006'],
    syncStatus: 'Corrected & runtime-verified (CI green); awaiting Product Owner disposition',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase5-start',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'Product Owner authorized Phase 5 — Backend Foundation & Persistence (narrow). #SCS implemented the client RemoteAdapter against the accepted StorageAdapter seam (parity proven: 7 tests — contract parity, export/import round-trip, optimistic-concurrency 409, idempotency, guarded reset) and wrote the Slim 4 PHP backend + MySQL schema/migrations + import tool (PHP/MySQL runtime is a host-verification item). Submitted ST-DLV-2026-006 for the SCS Backend Foundation & Persistence Review. Dev/test only — no authentication rollout, confidential data, integrations, or deployment.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: ['dec-scs-phase5'],
    documentsUpdated: [],
    syncStatus: 'Working — Phase 5 implementation (submitted for review)',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase4-approved',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'SCS Production Architecture Review — APPROVED (final). The corrected Phase 4 package (Rev 2) is accepted as the authoritative production-architecture planning baseline; ST-DLV-2026-005 accepted, the review gate closed (Approved), and the Phase 4 Assignment Directive completed & accepted (canonical ST-ADR identifier remains Product-Owner-pending). SCS is architecturally ready for Phase 5. This approval does NOT authorize production implementation, deployment, authentication rollout, data hosting, or integrations — Phase 5 requires a separate Product Owner directive.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-005', 'rgate-005', 'adr-006', 'dec-scs-phase4'],
    syncStatus: 'Approved — architectural baseline accepted',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase4-conditions',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'SCS Production Architecture Review — Approved with Conditions. Product Owner accepted the direction but required corrections (server-side canonical derivation, governed API commands, DB-enforced integrity, versioning/concurrency, audit vs Operational History boundary, finalized session auth, role/authority enforcement, import safety, hosting verification, narrowed Phase 5) before Phase 5. #SCS submitted the corrected package (Rev 2) for final review. Phase 5 not yet cleared; identifiers remain Product-Owner-pending.',
    source: 'Sonja (Product Owner) · #SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: [],
    documentsUpdated: ['dlv-005'],
    syncStatus: 'Approved with Conditions — corrected package resubmitted',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-scs-phase4',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'Product Owner confirmed SCS as an active internal platform product (in parallel with Kidlytics), closed the Phase 1 functional-demonstration scope (complete & accepted; production readiness not established), reconciled ProductOS as a legacy predecessor term, and authorized #SCS to prepare the Phase 4 SCS Production Architecture & Authorization Package (ST-DLV-2026-005) for review. No production implementation, migration, auth, or deployment is authorized.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs', 'prod-scs'],
    decisionsCreated: ['dec-scs-phase4'],
    documentsUpdated: ['dec-0003'],
    syncStatus: 'Authorized — architecture planning',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-phase1-closed',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Phase 1 functional demonstration closed — complete and accepted for its demonstration scope (SCS Home, Executive Snapshot, Team Command Center, supporting navigation and review workspace). Production readiness not established; production implementation not started.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs'],
    decisionsCreated: [],
    documentsUpdated: [],
    syncStatus: 'Accepted (demonstration scope)',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-cklr-research-assignment',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Product Owner approved and activated #CKL-R\'s competitive-research Assignment Directive as ST-ADR-2026-005 (deliverable ST-DLV-2026-004; Competitive Research Review gate). #CKL-R now derives as Working; Active Assignments 0 → 1. ST-ADR-2026-004 remains reserved. Findings are advisory only.',
    source: 'Sonja (Product Owner)',
    scope: 'Kidlytics',
    affectedSystems: ['prod-kidlytics', 'os-scs'],
    decisionsCreated: ['dec-cklr-research-assignment'],
    documentsUpdated: [],
    syncStatus: 'Active',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-cklr-activation',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Product Owner accepted Phase 3 (commit 0ecbf2a) and expressly activated AGENT-006/#CKL-R (Kidlytics Competitive Research Agent): ST-SD-006 Current, TM-009 Active in TEAM-001, activation event ST-OPH-2026-012. #CKL-R derives as Available — Awaiting Assignment. No research Assignment Directive was approved and no competitive research has begun.',
    source: 'Sonja (Product Owner)',
    scope: 'ShockTheory OS',
    affectedSystems: ['os-scs', 'prod-kidlytics'],
    decisionsCreated: ['dec-cklr-activation'],
    documentsUpdated: [],
    syncStatus: 'Approved',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-transition-kidlytics',
    code: 'ST-OS',
    date: '2026-07-25',
    summary: 'Milestone (Approved) — Transition from Constitutional Foundation to Product Execution. The Constitutional State Derivation initiative is complete; the SCS is now accepted operational infrastructure. Kidlytics is restored as the primary governed initiative. Reserved governance matters (AGENT-001..004 activation history, ST-OPH-2026-006..009, the reconciliation ST-ADR identifier, #CKL/#CKP evidence review) remain separate and do not delay Kidlytics.',
    source: 'Sonja (Product Owner)',
    scope: 'ShockTheory OS',
    affectedSystems: ['os-scs', 'prod-kidlytics'],
    decisionsCreated: [],
    documentsUpdated: [],
    syncStatus: 'Approved',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-accept-a773bd6',
    code: 'ST-REVIEW',
    date: '2026-07-25',
    summary: 'Product Owner accepted commit a773bd6 as the Phase 2 reconciliation baseline; the implementation-reconciliation cycle is closed and the Constitutional State Derivation Engine is Verified and Accepted. No agent was activated; ST-OPH-2026-006…009 remain Pending; no ST-ADR identifier assigned.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs'],
    decisionsCreated: [],
    documentsUpdated: [],
    syncStatus: 'Accepted',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-stlock',
    code: 'ST-LOCK',
    date: '2026-07-24',
    summary: 'Agent naming, authority boundaries, and interim decision source recorded (DEC-0001…DEC-0008).',
    source: 'Sonja (Product Owner)',
    scope: 'ShockTheory OS',
    affectedSystems: ['os-scs', 'os-sapdos'],
    decisionsCreated: ['dec-0001', 'dec-0002', 'dec-0003', 'dec-0004', 'dec-0005', 'dec-0006', 'dec-0007', 'dec-0008'],
    documentsUpdated: [],
    syncStatus: 'Recorded',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-phase1-review',
    code: 'ST-SYNC',
    date: '2026-07-24',
    summary: 'SCS Home and Executive Snapshot architecture built for Product Owner review.',
    source: '#SCS',
    scope: 'SCS',
    affectedSystems: ['os-scs'],
    decisionsCreated: [],
    documentsUpdated: [],
    syncStatus: 'Awaiting review',
    authorityStatus: 'reported',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-phase1',
    code: 'ST-REVIEW',
    date: '2026-07-24',
    summary: 'Phase 1 Executive Snapshot approved as the design baseline (visual direction).',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs'],
    decisionsCreated: [],
    documentsUpdated: [],
    syncStatus: 'Approved',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-phase0',
    code: 'ST-OS',
    date: '2026-07-24',
    summary: 'Phase 0 architecture approved; stack, data model, and deployment path locked.',
    source: 'Sonja (Product Owner)',
    scope: 'SCS',
    affectedSystems: ['os-scs'],
    decisionsCreated: [],
    documentsUpdated: [],
    syncStatus: 'Approved',
    authorityStatus: 'approved',
    demonstration: false,
    confidence: 'high',
  },
  {
    id: 'upd-cue-phase4',
    code: 'ST-LOCK',
    date: '',
    summary: 'Cue Experience Playbook — Phase 4 approved; Phase 5 authorized.',
    source: 'Kidlytics',
    scope: 'Kidlytics',
    affectedSystems: ['prod-kidlytics'],
    decisionsCreated: [],
    documentsUpdated: ['pub-cue'],
    syncStatus: 'Recorded',
    authorityStatus: 'approved',
    demonstration: true,
    confidence: 'medium',
    notes: 'Demonstration record. Date not specified — left empty rather than invented.',
  },
];

const nextActions: NextAction[] = [
  {
    id: 'next-chipn',
    recommendation: 'Resolve the Chip’n Workflow Playbook discovery and lifecycle decisions.',
    why: 'Chip’n is blocked in Discovery pending these decisions; resolving them unblocks its next phase.',
    affectedScope: 'pub-chipn',
    requiresOwnerApproval: true,
    authorityStatus: 'proposed',
    confidence: 'medium',
    notes: 'Seed recommendation — confirm or replace.',
  },
];

const empty: CollectionName[] = [
  'canonicalConcepts',
  'benchmarks',
  'risks',
  'reviewItems',
  'relationships',
];

export const seedWorkspace: WorkspaceBackup = {
  schemaVersion: SCHEMA_VERSION,
  exportedAt: '2026-07-24T00:00:00.000Z',
  isSeed: true,
  collections: {
    osSystems,
    products,
    publications,
    publicationPhases,
    gates: [...gates, ...reviewGates],
    decisions: interimDecisions,
    standingDirectives,
    assignmentDirectives,
    deliverables,
    operationalHistory,
    teams,
    teamMemberships,
    canonicalStatements,
    canonicalConcepts: [],
    aiCollaborators,
    assignments,
    benchmarks: [],
    risks: [],
    updates,
    artifacts,
    reviewItems: [],
    nextActions,
    relationships: [],
    ...Object.fromEntries(empty.map((k) => [k, []])),
  } as WorkspaceBackup['collections'],
};
